name: Docker Image CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v2
      with:
        login-server: 'quarantinetest.azurecr.io'
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker build . -t quarantinetest.azurecr.io/app2:latest
        docker push    quarantinetest.azurecr.io/app2:latest
        docker pull    quarantinetest.azurecr.io/app2:latest
